### ISSUE TITLE
Hi, I need help about modudculab_ros

### ISSUE THREAD

**Issue by dhkdn8825** [Jaeyoung-Lim/modudculab_ros#1]
i did $catkin build modudculab_ros
and that i got this error 

/home/sol/catkin_ws/src/modudculab_ros/src/pub_setpoints_traj.cpp:74:40: error: ‘mavros_msgs::SetMode::Response {aka struct mavros_msgs::SetModeResponse_<std::allocator<void> >}’ has no member named ‘success’
                 offb_set_mode.response.success){

**Comment by Jaeyoung-Lim** [comment]
Have you built mavros on your workspace?

**Comment by sjsanjsrh** [comment]
I have same problem.
I did 
`$ sudo apt-get install ros-kinetic-mavros ros-kinetic-mavros-extras`
but still has this error.

**Comment by dhkdn8825** [comment]
Modify cpp file. success --> mode_sent

**Comment by sjsanjsrh** [comment]
Thanks! solved this problem.

**Comment by Jaeyoung-Lim** [comment]
@dhkdn8825 Thanks for the comment. I will apply the changes for the fix
